on: [workflow_dispatch]
name: Generate Chainlist New
jobs:
  generate_chainlist:
    name: Generate Chainlist New
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          
      - name: Git Sumbodule Update
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 19.6.0

      - name: Install dependencies
        run: npm install
          
      - name: Run code to Generate Chainlist New
        working-directory: ./.github/workflows/utility
        run: node generate_chainlist_new.mjs
      
      - name: Add Commit Push
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: false
          commit_prefix: "[AUTO]"
          commit_message: "New chainlist.json Update"
          force: false
          target_branch: update/chainlist_new
      
      - name: Create A PR
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: update/chainlist_new
          target_branch: main
          title: New chainlist.json Update
          body: "**Automated pull request**"
          old_string: "**THIS IS AN AUTOMATED UPDATE OF CHAINLIST.JSON**"
          new_string: "** Automatic pull request**"
          get_diff: true
          ignore_users: "dependabot"
