name: Update Saved Pools Auto

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily
  workflow_dispatch:

jobs:
  update_saved_pools:
    name: Update Saved Pools Auto
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          
      - name: Git Sumbodule Update
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.6.0
          
      - name: Run code to Query Pools
        working-directory: ./.github/workflows/utility
        run: node queryPools.mjs

      - name: Add Commit Push
        run: |
          # Add, commit, and push changes
          git add .
          git commit -m "[AUTO] Query and Save Pools"
          git push origin update/query_pools
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
