on:
  pull_request:
    branches:
      - main
name: Pull request workflow
jobs:
  validate_assetlists:
    name: Validate assetlists
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
          
      - name: Install JSON-Schema-Validator
        run: npm install -g jsonschema

      - name: Validate Zone Assets schema
        run: find . -type f -name '*.assetlist.json' -exec jsonschema -i {} ./assetlist.schema.json \;
